# Introduction to numpy

In [1]:
# import numpy library
import numpy as np

In [3]:
# Create a range of numbers from 0 to 10
x = np.arange(0, 10)
print(x)


[0 1 2 3 4 5 6 7 8 9]


In [4]:
# create a new axis and reshape the array
x = np.arange(0, 10).reshape(1, 10)
print(x)

[[0 1 2 3 4 5 6 7 8 9]]


In [5]:
x.shape

(1, 10)

In [6]:
# add a new column to the array
x = np.arange(0, 10).reshape(10, 1)
print(x)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [7]:
x.shape

(10, 1)

In [9]:
# add a row to the array
x = np.arange(0, 10).reshape(1, 10)
print(x)
x.shape

[[0 1 2 3 4 5 6 7 8 9]]


(1, 10)

Why do we have 1D, 2D and 3D arrays in numpy? What are the differences between them? How to create them? How to access elements in them? How to perform operations on them? This notebook will answer all these questions.

why we need them ?
- 1D arrays are used to store a list of values.
- 2D arrays are used to store a matrix of values.
- 3D arrays are used to store a list of matrices.


In [10]:
# create a new array
x = np.arange(0, 10).reshape(2, 5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [11]:
x.shape

(2, 5)

In [14]:
# initialize a 2D array with zeros
x = np.zeros((2, 5)) # (rows, columns)
print(x)
x.shape

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


(2, 5)

In [15]:
# initialize a 2D array with ones
x = np.ones((2, 5)) # (rows, columns)
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
# initialize a 2D array with a specific value
x = np.full((2, 5), 5) # (rows, columns)
print(x)

[[5 5 5 5 5]
 [5 5 5 5 5]]


In [17]:
# create a indentity matrix
x = np.eye(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
x.dtype
x.shape

(5, 5)

In [20]:
type(x)

numpy.ndarray

In [21]:
# attributes of the array
print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)
print(x.itemsize)
print(x.data)


2
(5, 5)
25
float64
8


In [28]:
# basic operations
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

# elementwise addition
print(x + y)
print(np.add(x, y))

# elementwise subtraction
print(x - y)
print(np.subtract(x, y))

# elementwise multiplication
print(x * y)
print(np.multiply(x, y))

# elementwise division
print(x / y)
print(np.divide(x, y))

# elementwise square root
print(np.sqrt(x))

# matrix multiplication
print(x.dot(y))
print(np.dot(x, y))




[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [ ]:
# mathematical functions
