# Adnvance Numpy

In [1]:
# import numpy
import numpy as np

In [2]:
# create an empty array of 2,3
a = np.empty([2,3])
print(a)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [6.23043429e-307 2.22526399e-307 2.05837348e-312]]


In [3]:
# create an array of odd numbers between 0 and 10
b = np.arange(1,10,2)
print(b)

[1 3 5 7 9]


In [4]:
# create an array of even numbers between 0 and 10
c = np.arange(0,10,2)
print(c)

[0 2 4 6 8]


In [5]:
# Create a array of differnce of 4 from 1 to 30
d = np.arange(1,30,4)
print(d)

[ 1  5  9 13 17 21 25 29]


In [8]:
# craete an array of linspace between 1 and 10
e = np.linspace(0,10,9)
print(e)

[ 0.    1.25  2.5   3.75  5.    6.25  7.5   8.75 10.  ]


In [10]:
# deifne the data type of the array
f = np.array([1,2,3], dtype = int)
print(f)

[1 2 3]


In [11]:
# sorting the array
g = np.array([[3,7],[9,1]])
print(np.sort(g))


[[3 7]
 [1 9]]


In [12]:
# cretae two arrays and concatenate them
h = np.array([1,2,3])
i = np.array([4,5,6])
j = np.concatenate((h,i))
print(j)

[1 2 3 4 5 6]


In [13]:
# create a 2D array and split it into two arrays
k = np.array([[1,2,3],[4,5,6]])
l = np.split(k,2)
print(l)

[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [16]:
# create two 2D array and concatenate it
m = np.array([[1,2],[3,4]])
n = np.array([[5,6],[7,8]])
o = np.concatenate((m,n), axis = 1)
print(o)

[[1 2 5 6]
 [3 4 7 8]]


In [17]:
# create a 3d array
p = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(p)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [18]:
p.ndim

3

In [19]:
# reshape the array
q = np.array([[1,2,3],[4,5,6]])
print(q)
r = q.reshape(3,2)
print(r)


[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [20]:
# indexing and slicing
s = np.array([1,2,3,4,5,6,7])
print(s[1:5])


[2 3 4 5]


In [21]:
# use condition to get the values
t = np.array([1,2,3,4,5,6,7])
print(t[t>3])


[4 5 6 7]


In [22]:
# numpy indexing and slicing
u = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(u[0,1])

2


In [23]:
# make an array from another data or array
v = [1,2,3]
w = np.asarray(v)
print(w)



[1 2 3]


In [25]:
# create a matrix of random numbers
x = np.random.rand(3,5)
print(x)


[[0.15971174 0.20286264 0.88644113 0.59122813 0.50152157]
 [0.31721299 0.73111207 0.49146536 0.18894394 0.30416972]
 [0.56862549 0.26715903 0.62512954 0.25391494 0.69468905]]
